title: Conor McGrath
description: My analytical topics on a wide range of topics I find interesting.
author: Conor McGrath
email: cmcgrat3@nd.edu
phone: (267) 272-5761
github: https://github.com/Conor-McGrath
about: I am a Master's of Business Analytics student at Notre Dame and enjoy using data to answer life's questions.
disqus_shortname: programming
google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/conor-mcgrath-/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/Conor-McGrath"

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
# url: "http://localhost:4000"
url: "https://conor-mcgrath.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

theme: jekyll-theme-architect
